# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: TerraformInstaller@0
  inputs:
    terraformVersion: 'latest'
- task: TerraformCLI@0
  displayName: "Terrafrom Init"
  inputs:
    command: 'init'
- task: TerraformCLI@0
  displayName: 'terraform plan'
  inputs:
    command: 'plan'
    allowTelemetryCollection: false
    environmentServiceName: 'Azure Subscription 1'
    commandOptions: '-var secret=$(mySecretPipelineVar)'
