env                              = "dev"
resource_location                = "westeurope"
resource_group_prefix            = "dp"
storage_account_tier             = "Standard"
storage_account_replication_type = "LRS"
databricks_tier                  = "standard"
sql_admin_login                  = "sql_admin"
sql_admin_password               = ""
